version: '3.3'

services:

  # mysql
  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
    
    container_name: sample-kifu-mysql
    # env_file: 
    #   - ./mysql/mysql_env

    volumes:
      - ./reflect/db:/var/lib/mysql
    expose:
      - 3306
    tty: true

    # entrypoint: 
    #   - "mysqld" 
    #   - "-g" 
    #   - "demon off;"




  # Tomcat
  tomcat:
    build: 
      dockerfile: ./tomcat/Dockerfile
    container_name: sample-kifu-tomcat
    ports:
      - 8081:8080
    
    # depends_on:
    #   - mysql


    

# networks:
#     kifu-net:
#         external: true